### ISSUE TITLE
New main section: Security

### ISSUE THREAD

**Issue by pboushy** [Shufflepuck/MacAdminsDoc#8]
The primary purpose of opening this issue is to start a discussion on creating a new section called Security.
I propose the new section be organized in the following way:

Security
- Built-in (SIP, Gatekeeper, XProtect, FileVault)
- AntiVirus (Comparison between the "legacy AV vendors" - e.g. McAfee, MalwareBytes, ESET, SCEP)
- NextGen AntiVirus (Cylance, CarbonBlack, Santa)
- Data Loss Prevention (what exists, are any built first for Mac?)
- Industry Standards (CIS, NIST?)

I'd appreciate any and all feedback related to this including additional topics that may need to be added. I'll try to build out a basic structure and start to it.

**Comment by ftiff** [comment]
Hi @prbsparx 

That's a very good idea. 

I've added you as a contributor and created a sample Security/Antivirus/Microsoft-SCEP.rst 
Make sure to copy the Antivirus folder and update Security/index.rst and  Security/<newfolder>/index.rst to have it appear in the sidebar :)

Thank you!
